public class ArthimaticCalculationsHOMEWORK6 {
    public Integer Addition (integer x,integer y) {
        Integer z = x+y;
        System.debug( ' Number z is ' + z);
        return z;

    }
public Integer Subtraction (integer x,integer y) {
        Integer z = x-y;
        System.debug( ' Subtraction or two numbers is ' + z);
        return z;
}
public Integer Multiplication (integer x,integer y,integer m) {
    Integer z = x+y*m;
    System.debug( ' Multiplication or three numbers is ' + z);
    return z;
}
}