public class Cars {
    public void switchOn() {
        System.debug('Starting the car ');
        }
        public void durma() {
        System.debug('Hello tir tir');
        }
        public void test() {
            String tes1 = ' almagul ';
            Integer tes2 = tes1.length();
            System.debug(tes2); 
       
        }
        public void test10() {
            String tes1 = ' almagul ';
            String tes2 = 'ALMA';
            Boolean tes3 = tes1.equals(tes2);
            System.debug(tes3); 
        
}
}