public class SalesforceDeveloperNazik {
    public void myFistCode() {
        System.debug( ' Turkmenistan ');
        System.debug( ' Ertugrul Dirilis ' );
        System.debug( ' Guyz ' );

    }
     public void myFovorite() {
        String city = ' Chicago ';
        Integer num = 7;
        System.debug( ' I am in  ' + city + ' my fovorite number is ' + num);
       

    }
     public void myPrint(String abc) {
        system.debug(abc);

    }
      public void cityinformartion () {

        String info = ' Norwey ';
        String city =  ' Alp daglar ' ;
        String all = info + city;
        system.debug(' Goremek istegim sehir  ' + all);


      }
      public void StringMethods () {
        String str1 = ' I am Salesforce Developer ';
        System.debug( ' str1  > ' + str1);
        Boolean check = str1.contains( 'force');
        System.debug( ' check  > ' + check);
        String upper = str1.toUpperCase();
        System.debug( ' check  > ' + upper);
         Integer upper1 = str1.length();
        System.debug( ' check  > ' + upper1);

       


}
}