public class CheckDatatypes {
    public void MethodBoolean() {
        Boolean checkBoolean = true;
        System.debug(' chechBoolean is ==> ' + checkBoolean) ;


    }
    public void MethodInteger() {
        Integer varfirst = 10;
        Integer varsecond =20;
        System.debug(' Var1 is ==> ' + varfirst + ' and Var2 is ' + varsecond + '.');
        

    }
    public void Stringmethod () {
        String varName = 'Name';
        String var2Name = 'Dovran';        
        System.debug(' What is your ' + varName + ' ? ' +  ' My name is  ' + var2Name + '.');

}
}