DLMDemo.dmlInsertDemo_stndObj();
DLMDemo.dmlInsertDemo_customObj();
DLMDemo.dmlUpdate_standartObj();
DLMDemo.dmlUpdateDemo_standartObJ3();
DLMDemo.dmlUpdateDemo_standartObJ4();
DLMDemo.dmlInsertDemo_cstObj5();
DLMDemo.dmlmultypileRecordsInsert_right1();
DLMDemo.dmlMultipleRecordInsert_right2();
DLMDemo.dmlMultipleRecordUpdate_right1();
DLMDemo.dmlMultipleRecordUpdate_right2();
DLMDemo.dmlInsertDemo_stndObj2();

delete [ SELECT Id,name FROM Account WHERE CreatedDate = TODAY limit 50];
