




List<integer> listInteger = new List<integer>();
listInteger.add(10);//0
listInteger.add(15);//1
listInteger.add(21);//2
listInteger.add(15);//3
listInteger.add(15);//4
integer sumofList = ListDemo.add(listInteger);
system.debug('sum of list is ' + sumofList);





ListDemo.integerListALL();

ListDemo.allCats();

string c1 = ListDemo.CandidateList(2);
System.debug(' c1 . ' + c1);
string c2 = ListDemo.CandidateList(5);
System.debug(' c2 . ' + c2);


// ListDemo.randomIntegerList();